const $ = (s, el=document) => el.querySelector(s);
const $$ = (s, el=document) => [...el.querySelectorAll(s)];
const icons = {
  dashboard:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
  leads:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16M6 10h12M9 15h6M11 20h2"/></svg>',
  clients:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
  tasks:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="4" width="18" height="17" rx="3"/><path d="M8 2v4M16 2v4M3 10h18M8 15l2 2 4-4"/></svg>',
  analytics:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',
  settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.1A1.7 1.7 0 0 0 8.5 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3V9.6h.1A1.7 1.7 0 0 0 4.6 8.5a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.5 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.13.38.34.72.6 1 .3.3.68.45 1.1.4h.1v4h-.1A1.7 1.7 0 0 0 19.4 15z"/></svg>',
  search:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
  plus:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>',
  bell:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>',
  menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',
  trend:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 17 6-6 4 4 8-9"/><path d="M15 6h6v6"/></svg>',
  money:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 9h.01M17 15h.01M9 12h6"/></svg>',
  check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 4 4L19 6"/></svg>'
};

const seed = {
  leads:[
    {id:1,name:'Анна Смирнова',company:'Nordline Studio',phone:'+7 912 340-18-22',email:'anna@nordline.ru',stage:'new',amount:185000,manager:'МК',date:'Сегодня, 12:40'},
    {id:2,name:'Илья Волков',company:'Vector Lab',phone:'+7 922 014-62-10',email:'ilya@vectorlab.ru',stage:'contact',amount:320000,manager:'ЕА',date:'Сегодня, 10:15'},
    {id:3,name:'Мария Орлова',company:'Orion Market',phone:'+7 999 118-42-09',email:'maria@orion.ru',stage:'proposal',amount:246000,manager:'МК',date:'Вчера, 18:05'},
    {id:4,name:'Денис Крылов',company:'Kraft Group',phone:'+7 912 775-91-02',email:'d.krylov@kraft.ru',stage:'won',amount:580000,manager:'АП',date:'Вчера, 15:20'},
    {id:5,name:'Олег Фомин',company:'Pixel Works',phone:'+7 982 401-37-18',email:'oleg@pixelworks.ru',stage:'contact',amount:97000,manager:'ЕА',date:'17 июля'},
    {id:6,name:'Софья Белова',company:'Astra Tech',phone:'+7 905 810-23-44',email:'sofia@astratech.ru',stage:'new',amount:410000,manager:'МК',date:'16 июля'}
  ],
  tasks:[
    {id:1,title:'Позвонить Анне Смирновой',info:'Nordline Studio · Новый лид',due:'Сегодня, 14:00',urgent:true,done:false},
    {id:2,title:'Подготовить коммерческое предложение',info:'Orion Market · 246 000 ₽',due:'Сегодня, 17:30',done:false},
    {id:3,title:'Провести демонстрацию продукта',info:'Vector Lab · Google Meet',due:'Завтра, 11:00',done:false},
    {id:4,title:'Отправить договор на подпись',info:'Kraft Group · Сделка №1048',due:'22 июля',done:false},
    {id:5,title:'Обновить карточку клиента',info:'Pixel Works · Контакты',due:'23 июля',done:true},
    {id:6,title:'Собрать отчёт по конверсии',info:'Июль · Отдел продаж',due:'25 июля',done:true}
  ]
};
let state = JSON.parse(localStorage.getItem('mkflow-data') || 'null') || structuredClone(seed);
let currentPage = location.hash.slice(1) || 'dashboard';
let leadView = 'table';
const pages = {dashboard:'Обзор',leads:'Лиды',clients:'Клиенты',tasks:'Задачи',analytics:'Аналитика',settings:'Настройки'};
const stages = {new:'Новые',contact:'В работе',proposal:'Предложение',won:'Успешно'};
const money = n => new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const initials = name => name.split(' ').map(x=>x[0]).slice(0,2).join('');
const save = () => localStorage.setItem('mkflow-data', JSON.stringify(state));

function shell(){
  $('#app').innerHTML = `<div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><img class="brand-logo" src="assets/brand-avatar.jpg"><div><div class="brand-title">MK Flow</div><div class="brand-sub">sales crm</div></div></div>
      <div class="nav-label">Рабочее пространство</div><nav class="nav">${Object.entries(pages).slice(0,5).map(([k,v])=>`<button class="nav-btn ${currentPage===k?'active':''}" data-page="${k}"><span class="nav-icon">${icons[k]}</span>${v}${k==='tasks'?'<b class="nav-badge">'+state.tasks.filter(t=>!t.done).length+'</b>':''}</button>`).join('')}</nav>
      <div class="nav-label">Система</div><nav class="nav"><button class="nav-btn ${currentPage==='settings'?'active':''}" data-page="settings"><span class="nav-icon">${icons.settings}</span>Настройки</button></nav>
      <div class="sidebar-foot"><div class="user-mini"><img class="avatar" src="assets/brand-avatar.jpg"><div><div class="user-name">Максим Ковалёв</div><div class="user-role">Администратор</div></div></div></div>
    </aside>
    <main class="main"><header class="topbar"><button class="icon-btn menu-btn" id="menu">${icons.menu}</button><div class="search">${icons.search}<input id="global-search" placeholder="Поиск по CRM..."><span class="shortcut">⌘ K</span></div><div class="top-actions"><button class="icon-btn" id="quick-add">${icons.plus}</button><button class="icon-btn" id="notify">${icons.bell}<i class="notification-dot"></i></button><img class="avatar" src="assets/brand-avatar.jpg"></div></header><div id="content"></div>
    <nav class="bottom-nav">${Object.entries(pages).slice(0,5).map(([k,v])=>`<button class="bottom-nav-btn ${currentPage===k?'active':''}" data-mobile-page="${k}"><span>${icons[k]}</span><small>${v}</small></button>`).join('')}</nav></main>
  </div>`;
  bindShell(); renderPage();
}
function bindShell(){
  $$('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
  $('#menu').onclick=()=>{ $('.sidebar').classList.toggle('open'); toggleOverlay($('.sidebar').classList.contains('open')); };
  $('#quick-add').onclick=()=>openLeadModal();
  $('#notify').onclick=()=>toast('У вас 3 новых уведомления');
  $('#global-search').oninput=e=>{ if(e.target.value.length>1){currentPage='leads'; renderNav(); renderLeads(e.target.value)} };
  $$('[data-mobile-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.mobilePage));
  document.addEventListener('keydown', e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#global-search').focus()}});
}
function toggleOverlay(show){let o=$('.mobile-overlay');if(show&&!o){o=document.createElement('div');o.className='mobile-overlay';o.onclick=()=>{$('.sidebar').classList.remove('open');o.remove()};document.body.append(o)}else if(!show&&o)o.remove()}
function navigate(p){currentPage=p;location.hash=p;$('.sidebar').classList.remove('open');toggleOverlay(false);renderNav();renderPage()}
function renderNav(){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));$$('.bottom-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.mobilePage===currentPage))}
function pageHead(eyebrow,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><div class="subtitle">${sub}</div></div><div class="head-actions">${actions}</div></div>`}
function renderPage(){const c=$('#content');c.innerHTML='<div class="page page-enter"></div>';({dashboard:renderDashboard,leads:renderLeads,clients:renderClients,tasks:renderTasks,analytics:renderAnalytics,settings:renderSettings}[currentPage]||renderDashboard)()}
function renderDashboard(){
  const p=$('.page'), revenue=state.leads.filter(x=>x.stage==='won').reduce((a,b)=>a+b.amount,0), pipeline=state.leads.reduce((a,b)=>a+b.amount,0);
  p.innerHTML=pageHead('Главная','Добро пожаловать, Максим','Вот что происходит с вашими продажами сегодня',`<button class="btn">Экспорт</button><button class="btn btn-primary" id="add">${icons.plus} Новый лид</button>`)+`
  <div class="grid stats">
    ${stat('leads','Всего лидов',state.leads.length,'+12.4%')}${stat('money','Выручка',money(revenue),'+18.2%')}${stat('trend','Воронка',money(pipeline),'+7.8%')}${stat('tasks','Активные задачи',state.tasks.filter(t=>!t.done).length,'−2.1%','down')}
  </div><div class="grid dashboard-grid"><section class="card chart-card"><div class="card-head"><div><div class="card-title">Динамика продаж</div><div class="card-subtitle">Выручка и новые сделки</div></div><select class="select"><option>Последние 7 дней</option><option>Этот месяц</option></select></div><div class="chart">${[42,58,49,72,61,88,78].map((h,i)=>`<div class="bar-wrap"><i class="bar secondary" style="--h2:${h-18}%"></i><i class="bar" style="--h:${h}%;animation-delay:${i*.06}s"></i></div>`).join('')}</div><div class="chart-labels">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span>${x}</span>`).join('')}</div></section>
  <section class="card activity-card"><div class="card-head"><div><div class="card-title">Последняя активность</div><div class="card-subtitle">Обновления команды</div></div></div><div class="activity-list">${[['А','Анна стала новым лидом','Nordline Studio','2 мин'],['₽','Сделка успешно закрыта','Kraft Group · 580 000 ₽','1 ч'],['М','Мария открыла предложение','Orion Market','3 ч'],['З','Задача выполнена','Обновить базу контактов','5 ч'],['И','Илья перешёл в работу','Vector Lab','Вчера']].map(a=>`<div class="activity"><div class="activity-icon">${a[0]}</div><div><strong>${a[1]}</strong><span>${a[2]}</span></div><time>${a[3]}</time></div>`).join('')}</div></section></div>`;
  $('#add').onclick=()=>openLeadModal();
}
function stat(icon,label,value,trend,cls=''){return `<div class="card stat-card"><div class="stat-top"><div class="stat-icon">${icons[icon]}</div><div class="trend ${cls}">${trend}</div></div><div class="stat-value">${value}</div><div class="stat-label">${label}</div></div>`}
function renderLeads(query=''){
  const p=$('.page')||$('#content').appendChild(Object.assign(document.createElement('div'),{className:'page page-enter'}));
  const list=state.leads.filter(x=>(x.name+x.company+x.email).toLowerCase().includes(query.toLowerCase()));
  p.innerHTML=pageHead('Продажи','Лиды и сделки','Управляйте воронкой и контролируйте каждый контакт',`<button class="btn" id="view-toggle">${leadView==='table'?'Воронка':'Таблица'}</button><button class="btn btn-primary" id="add">${icons.plus} Добавить лид</button>`)+`<div class="toolbar"><div class="toolbar-search">${icons.search}<input id="lead-search" value="${query}" placeholder="Найти лид или компанию..."></div><div class="filter-chips"><button class="chip active" data-filter="all">Все</button>${Object.entries(stages).map(([k,v])=>`<button class="chip" data-filter="${k}">${v}</button>`).join('')}</div></div><div id="lead-content">${leadView==='table'?leadTable(list):kanban(list)}</div>`;
  $('#add').onclick=()=>openLeadModal();$('#view-toggle').onclick=()=>{leadView=leadView==='table'?'kanban':'table';renderLeads(query)};$('#lead-search').oninput=e=>renderLeadContent(e.target.value,'all');$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLeadContent($('#lead-search').value,b.dataset.filter)});bindDealActions();
}
function renderLeadContent(q,filter){const list=state.leads.filter(x=>(x.name+x.company+x.email).toLowerCase().includes(q.toLowerCase())&&(filter==='all'||x.stage===filter));$('#lead-content').innerHTML=leadView==='table'?leadTable(list):kanban(list);bindDealActions()}
function leadTable(list){return `<div class="card table-card"><table class="table"><thead><tr><th>Клиент</th><th>Этап</th><th>Сумма</th><th>Телефон</th><th>Менеджер</th><th>Обновлено</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td><div class="person"><div class="person-avatar">${initials(x.name)}</div><div><strong>${x.name}</strong><small>${x.company}</small></div></div></td><td><span class="status ${x.stage}">${stages[x.stage]}</span></td><td class="amount">${money(x.amount)}</td><td class="muted">${x.phone}</td><td><span class="mini-avatar">${x.manager}</span></td><td class="muted">${x.date}</td><td><button class="more-btn edit-lead" data-id="${x.id}">•••</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Ничего не найдено</td></tr>'}</tbody></table></div>`}
function kanban(list){return `<div class="kanban">${Object.entries(stages).map(([stage,label],i)=>{const arr=list.filter(x=>x.stage===stage);return `<div class="kanban-col" data-stage="${stage}"><div class="kanban-head"><i style="--col:${['#ffc400','#60a5fa','#c084fc','#4ade80'][i]}"></i>${label}<span class="kanban-count">${arr.length}</span></div>${arr.map(x=>`<article class="deal-card edit-lead" draggable="true" data-id="${x.id}"><div class="deal-title">${x.name}</div><div class="deal-company">${x.company}</div><div class="deal-meta"><span class="deal-price">${money(x.amount)}</span><span class="mini-avatar">${x.manager}</span></div></article>`).join('')}</div>`}).join('')}</div>`}
function bindDealActions(){$$('.edit-lead').forEach(b=>{b.onclick=()=>openLeadModal(+b.dataset.id);b.ondragstart=()=>b.classList.add('dragging');b.ondragend=()=>b.classList.remove('dragging')});$$('.kanban-col').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();const d=$('.dragging');if(!d)return;state.leads.find(x=>x.id===+d.dataset.id).stage=c.dataset.stage;save();renderLeads();toast('Этап сделки обновлён')}})}
function renderClients(){const p=$('.page'), won=state.leads.filter(x=>x.stage==='won'||x.stage==='proposal');p.innerHTML=pageHead('Контакты','Клиенты','Единая база клиентов и история взаимодействий',`<button class="btn btn-primary" id="add">${icons.plus} Новый клиент</button>`)+`<div class="grid stats">${stat('clients','Всего клиентов',won.length,'+8.4%')}${stat('money','Средний чек',money(Math.round(won.reduce((a,b)=>a+b.amount,0)/(won.length||1))),'+6.1%')}${stat('trend','Повторные продажи','34%','+3.2%')}${stat('tasks','На сопровождении','12','+2')}</div>${leadTable(won)}`;$('#add').onclick=()=>openLeadModal();bindDealActions()}
function renderTasks(){const p=$('.page'),done=state.tasks.filter(t=>t.done).length,percent=Math.round(done/state.tasks.length*100);p.innerHTML=pageHead('Планирование','Задачи','Фокусируйтесь на важных действиях и сроках',`<button class="btn btn-primary" id="add-task">${icons.plus} Новая задача</button>`)+`<div class="grid tasks-layout"><section class="card task-list">${state.tasks.map(t=>`<div class="task-item ${t.done?'completed':''}"><button class="check ${t.done?'checked':''}" data-task="${t.id}">${t.done?icons.check:''}</button><div><div class="task-title">${t.title}</div><div class="task-info">${t.info}</div></div><span class="due ${t.urgent?'urgent':''}">${t.due}</span></div>`).join('')}</section><aside class="card progress-card"><div class="card-title">Прогресс на неделю</div><div class="ring-chart" style="--progress:${percent}%"><div class="ring-value">${percent}%<small>выполнено</small></div></div><div class="legend-row"><span>Выполнено</span><strong>${done}</strong></div><div class="legend-row"><span>В работе</span><strong>${state.tasks.length-done}</strong></div><div class="legend-row"><span>Всего задач</span><strong>${state.tasks.length}</strong></div></aside></div>`;$$('[data-task]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===+b.dataset.task);t.done=!t.done;save();renderTasks();toast(t.done?'Задача выполнена':'Задача возвращена в работу')});$('#add-task').onclick=openTaskModal}
function renderAnalytics(){const p=$('.page');p.innerHTML=pageHead('Отчёты','Аналитика продаж','Ключевые показатели бизнеса в реальном времени',`<button class="btn">Скачать отчёт</button>`)+`<div class="grid analytics-grid"><section class="card metric-card wide"><div class="card-head"><div><div class="card-title">Выручка по месяцам</div><div class="card-subtitle">Динамика за последние 6 месяцев</div></div><strong class="amount">2 840 000 ₽</strong></div><div class="spark"><svg viewBox="0 0 600 100" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ffc400" stop-opacity=".3"/><stop offset="1" stop-color="#ffc400" stop-opacity="0"/></linearGradient></defs><path d="M0 85 C60 80,70 50,130 60 S210 80,270 38 S360 55,410 25 S510 40,600 8 V100 H0Z" fill="url(#g)"/><path d="M0 85 C60 80,70 50,130 60 S210 80,270 38 S360 55,410 25 S510 40,600 8" fill="none" stroke="#ffc400" stroke-width="3"/></svg></div></section><section class="card metric-card"><div class="card-title">Конверсия воронки</div><div class="funnel"><div class="funnel-step"><span>Новые лиды</span><strong>124</strong></div><div class="funnel-step"><span>В работе</span><strong>86</strong></div><div class="funnel-step"><span>Предложение</span><strong>48</strong></div><div class="funnel-step"><span>Продажа</span><strong>29</strong></div></div></section>${stat('trend','Конверсия','23.4%','+2.8%')}${stat('money','Средний цикл','8.2 дня','−1.3 дня')}${stat('clients','Новых клиентов','42','+14.6%')}</div>`}
function renderSettings(){const p=$('.page');p.innerHTML=pageHead('Система','Настройки','Управляйте профилем и параметрами рабочего пространства')+`<div class="grid settings-grid"><aside class="card settings-nav"><button class="settings-tab active">Профиль</button><button class="settings-tab">Компания</button><button class="settings-tab">Уведомления</button><button class="settings-tab">Интеграции</button><button class="settings-tab">Безопасность</button></aside><section class="card settings-content"><div class="brand-preview"><img src="assets/brand-avatar.jpg"><div><div class="card-title">Логотип рабочего пространства</div><div class="subtitle">Используется в меню и профиле CRM</div></div></div><form id="settings-form" class="form-grid"><div class="field"><label>Имя</label><input class="input" value="Максим"></div><div class="field"><label>Фамилия</label><input class="input" value="Ковалёв"></div><div class="field"><label>Email</label><input class="input" value="admin@mkflow.ru"></div><div class="field"><label>Телефон</label><input class="input" value="+7 912 000-00-00"></div><div class="field full"><label>Название компании</label><input class="input" value="MK Flow"></div><div class="field full"><label>О компании</label><textarea class="input">Современная команда продаж и клиентского сервиса.</textarea></div><div class="field full"><div><button class="btn btn-primary">Сохранить изменения</button></div></div></form></section></div>`;$('#settings-form').onsubmit=e=>{e.preventDefault();toast('Настройки сохранены')};$$('.settings-tab').forEach(b=>b.onclick=()=>{$$('.settings-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Раздел «'+b.textContent+'» открыт')})}
function openLeadModal(id){const lead=id?state.leads.find(x=>x.id===id):null;openModal(lead?'Редактировать лид':'Новый лид',`<form id="lead-form" class="form-grid"><div class="field"><label>Имя и фамилия</label><input class="input" name="name" required value="${lead?.name||''}" placeholder="Анна Смирнова"></div><div class="field"><label>Компания</label><input class="input" name="company" required value="${lead?.company||''}" placeholder="Название компании"></div><div class="field"><label>Телефон</label><input class="input" name="phone" value="${lead?.phone||''}" placeholder="+7 900 000-00-00"></div><div class="field"><label>Email</label><input class="input" type="email" name="email" value="${lead?.email||''}" placeholder="mail@company.ru"></div><div class="field"><label>Сумма сделки</label><input class="input" type="number" name="amount" value="${lead?.amount||''}" placeholder="150000"></div><div class="field"><label>Этап</label><select class="input" name="stage">${Object.entries(stages).map(([k,v])=>`<option value="${k}" ${lead?.stage===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Комментарий</label><textarea class="input" placeholder="Важные детали по клиенту"></textarea></div><div class="field full modal-actions">${lead?'<button type="button" class="btn" id="delete-lead">Удалить</button>':''}<button type="button" class="btn close-modal">Отмена</button><button class="btn btn-primary">${lead?'Сохранить':'Добавить лид'}</button></div></form>`);$('#lead-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.amount=+d.amount||0;if(lead)Object.assign(lead,d);else state.leads.unshift({id:Date.now(),...d,manager:'МК',date:'Только что'});save();closeModal();currentPage='leads';renderNav();renderPage();toast(lead?'Данные лида обновлены':'Новый лид добавлен')};if(lead)$('#delete-lead').onclick=()=>{state.leads=state.leads.filter(x=>x.id!==id);save();closeModal();renderPage();toast('Лид удалён')}}
function openTaskModal(){openModal('Новая задача',`<form id="task-form" class="form-grid"><div class="field full"><label>Название задачи</label><input class="input" name="title" required placeholder="Что нужно сделать?"></div><div class="field full"><label>Описание</label><input class="input" name="info" placeholder="Клиент или детали"></div><div class="field"><label>Срок</label><input class="input" name="due" value="Сегодня, 18:00"></div><div class="field"><label>Приоритет</label><select class="input" name="urgent"><option value="">Обычный</option><option value="1">Высокий</option></select></div><div class="field full modal-actions"><button type="button" class="btn close-modal">Отмена</button><button class="btn btn-primary">Добавить задачу</button></div></form>`);$('#task-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.tasks.unshift({id:Date.now(),...d,urgent:!!d.urgent,done:false});save();closeModal();renderTasks();toast('Задача добавлена')}}
function openModal(title,body){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close-btn close-modal">×</button></div><div class="modal-body">${body}</div></div>`;document.body.append(wrap);wrap.onclick=e=>{if(e.target===wrap)closeModal()};$$('.close-modal',wrap).forEach(b=>b.onclick=closeModal);document.addEventListener('keydown',escModal)}
function escModal(e){if(e.key==='Escape')closeModal()}function closeModal(){$('.modal-backdrop')?.remove();document.removeEventListener('keydown',escModal)}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;$('#toast-root').append(t);setTimeout(()=>{t.style.opacity=0;t.style.transform='translateX(15px)';setTimeout(()=>t.remove(),250)},2600)}
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(pages[p]){currentPage=p;renderNav();renderPage()}});
shell();
